version: 0.0
os: linux
files:
-  source: /
   destination: /var/www/weatherapp
hooks:
BeforeInstall:
   - location: /var/www/weatherapp/scripts/cleans
     timeout: 10
     runas: root
AfterInstall:
   - location: /var/www/weatherapp/scripts/app-start.sh
     timeout: 1200
     runas: root