# Do not change the version. this the version of aws buildspec and not the file version
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre-build:
    commands:
      - echo 'installing source npm dependencies'
      - npm install
  build:
    commonds:
      - echo build stage completed 'date'
  post_build:
    commonds:
      - echo post build stage 'date'
artifacts:
  files:
    - "**/*"